In [1]:
! pip install numpy


     |████████████████████████████████| 17.0 MB 5.1 MB/s eta 0:00:01    |█████████                       | 4.8 MB 2.9 MB/s eta 0:00:05
You should consider upgrading via the '/Users/zopper/Desktop/Python/ML-Basics/mlenv/bin/python3 -m pip install --upgrade pip' command.


In [5]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
print(type(a))

# tells the dimension of the numpy array
print(a.shape)



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2]
 [2 6]
 [3 4]
 [4 5]
 [0 5]]
<class 'numpy.ndarray'>
(5, 2)


# 2D ARRAY


In [6]:
b = np.array([[1,2],[2,6],[3,4],[4,5],[0,5]])
print(b)
print(type(b))
print(b.shape)
print(b[1][1])

[[1 2]
 [2 6]
 [3 4]
 [4 5]
 [0 5]]
<class 'numpy.ndarray'>
(5, 2)
6


# Creating Custom Arrays
## 1. ZERO ARRAY
### np.zeros((no_of_rows,no_of_columns))

## 2. ONES ARRAY
### np.ones((no_of_rows,no_of_columns))

## 3. CONSTANT NUMBER ARRAY
### np.full((no_of_rows,no_of_columns),number)

## 4. IDENTITY MATRIX
### np.eye(size)

## 5. RANDOM MATRIX
### np.random.random((no_of_rows,no_of_columns))

In [27]:
# ZERO ARRAY
# print(np.zeros((3,3)))

# print(np.ones((3,3)))

# randomMatrix = np.random.random((2,3))
print(randomMatrix)
print("#"*100)
print(randomMatrix[ : ,0])

[[0.19450727 0.39270512 0.30917958]
 [0.59703119 0.71306419 0.26600976]]
####################################################################################################
[0.19450727 0.59703119]


# MATHEMATICAL OPERATIONS ON MATRICES


In [29]:
# ADDITION
a = np.array([[1,2],[2,4]])
b = np.array([[1,2],[2,4]])
print(a+b)
print(np.add(a,b))

[[2 4]
 [4 8]]
[[2 4]
 [4 8]]


In [30]:
# SUBTRACTION
a = np.array([[1,2],[2,4]])
b = np.array([[1,2],[2,4]])
print(a-b)
print(np.subtract(a,b))

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


In [31]:
# MULTIPLICATION
a = np.array([[1,2],[2,4]])
b = np.array([[1,2],[2,4]])
print(a*b)
print(np.multiply(a,b))

[[ 1  4]
 [ 4 16]]
[[ 1  4]
 [ 4 16]]


In [33]:
# DIVISION
a = np.array([[1,2],[2,4]])
b = np.array([[1,2],[2,4]])
print(a//b)
print(np.divide(a,b))

[[1 1]
 [1 1]]
[[1. 1.]
 [1. 1.]]


In [35]:
# SQUARE ROOT
a = np.array([[1,2],[2,4]])
b = np.array([[1,2],[2,4]])
print(np.sqrt(a))

[[1.         1.41421356]
 [1.41421356 2.        ]]


# DOT PRODUCT

In [36]:
# DOT PRODUCT
a = np.array([[1,2],[2,4]])
b = np.array([[1,2],[2,4]])
print(np.dot(a,b))
print(a.dot(b))

[[ 5 10]
 [10 20]]
[[ 5 10]
 [10 20]]


# SUM FUNCTION
## np.sum((matrix),axis=0) axis = 0 (columnwise add)
##                                           axis =1 (rowwise)

In [37]:
a = np.array([[1,2],[2,4]])
print(np.sum(a,axis=1))

[3 6]


# Stacking of Arrays
## np.stack((array1,array2),axis = 0,1)

In [47]:
# Stacking of Arrays
a = np.array([1,23,4,5,6])
b = np.array([3,2,4,5,6])
b = b**2
print(b)

print(np.stack((a,b),axis=1))
np.stack((a,b),axis=1).shape


[ 9  4 16 25 36]
[[ 1  9]
 [23  4]
 [ 4 16]
 [ 5 25]
 [ 6 36]]


(5, 2)

# RESHAPING NP ARRAY
## np.reshape((rowxcolumn))

In [56]:
# Reshaping np Array
a = np.array([[1,3],[23,4],[5,6]])
b = np.array([3,2,4,5,6])
print(a.shape)
a = a.reshape((6,1))
print(a)
print(a.shape)

(3, 2)
[[ 1]
 [ 3]
 [23]
 [ 4]
 [ 5]
 [ 6]]
(6, 1)



# ARRANGE FUNCTION
## np.arrange(number of elements)

In [58]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


# NUMPY RANDOM MODULE
## 1. RAND: RANDOM VALUES IN A GIVEN SHAPE
## 2. RANDN: RETURN A SAMPLE FROM THE STANDARD NORMAL DISTRIBUTION
## 3. RANDINT : RETURN RANDOM INTS FROM LOW TO HIGH RANGE AS GIVEN
## 4. RANDOM : RETURN RANDOM FLOATS IN HALF OPEN INTERVALS [0.0,1.0]
## 5. CHOICE : GENERATES A RANDOM SAMPLE FROM A GIVEN 1D ARRAY
## 6. SHUFFLE: SHUFFLES CONTENTS OF A SEQUENCE

In [67]:
a = np.arange(10)


np.random.shuffle(a)
print(a)

np.random.randn(2,3)

np.random.randint(5,10,3)
np.random.choice(a)

[1 3 4 6 9 5 7 2 0 8]


8

# STASTICAL METHODS IN NUMPY
## 1. min,max
## 2. mean
## 3. median
## 4. average,variance,standard deviation

In [72]:
a = np.array([[1,2,3,4],[6,4,3,2]])
print(a)
print(np.min(a))
print(np.min(a,axis = 0))
print(np.min(a,axis = 1))

print(np.max(a))
print(np.max(a,axis = 0))
print(np.max(a,axis = 1))


print(np.mean(a))

print(np.mean(a,axis = 0))
print(np.mean(a,axis = 1))

print(np.median(a))


print("#"*100)
#  Standard Deviation
print(np.std(x))

#  Variance 
print(np.std(x)** 2)

[[1 2 3 4]
 [6 4 3 2]]
1
[1 2 3 2]
[1 2]
6
[6 4 3 4]
[4 6]
3.125
[3.5 3.  3.  3. ]
[2.5  3.75]
3.0
####################################################################################################
3.0
3.5
1.4142135623730951
2.0000000000000004


# MEAN VS AVERAGE
## AVERAGE INCLUDES THE WEIGHTS ASSOCIATED WITH THE ARRAY

In [ ]:
x = np.array([1,2,3,4,5])
w = np.array([2,3,4,5,6])
print(np.mean(x))
print(np.average(x,weights=w))